### PR TITLE
Change docs, storybook for disabled button

### PR DESCRIPTION
**Pull request by emi420**
For the `disabled` Button the correct way to use the property is:

`<hot-button disabled>`

Instead of:

`<hot-button disabled="true">`

Because anything inside the argument's value will result in a "True" value (because it's a string).

I modified the README.md file with this change and also added the property to the component's story, because it wasn't working when using the "disabled" switch.

### CODE REVIEW

**Comment by JoltCode** [comment]
Ah perfect, thanks Emi! LGTM! 👍

**Review by JoltCode — APPROVED** [review]
LGTM! 👍

**Comment by spwoodcock** [comment]
Nice, thanks!

I think you might have autoformatting turned on in your IDE by the way - watch out it doesn't conflict with the configured pre-commit hooks.

To keep consistent, install the pre-commit hooks:
```bash
pip install pre-commit
pre-commit install
```

**Comment by emi420** [comment]
Oh yes @spwoodcock  I might be the case! , for the `.github/ISSUE_TEMPLATE/feature_request.md` file I made the change manually because the test was failing. But for the `tsconfig.json` it was changed automatically.

**Pull request merged**
